character_ascension_requirements = [
    {
        "Wanderer's Advice": 5,
        "Adventurer's Experience": 3,
        "Hero's Wit": 34,
        "Mora": 20000,
        "BossItem": 0,
        "LocalSpecialty": 3,
        "Sliver": 1,
        "Fragment": 0,
        "Chunk": 0,
        "Gemstone": 0,
        "EnhancementMaterial1": 3,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 0,
    },
    {
        "Wanderer's Advice": 0,
        "Adventurer's Experience": 0,
        "Hero's Wit": 29,
        "Mora": 40000,
        "BossItem": 2,
        "LocalSpecialty": 10,
        "Sliver": 0,
        "Fragment": 3,
        "Chunk": 0,
        "Gemstone": 0,
        "EnhancementMaterial1": 15,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 0,
    },
    {
        "Wanderer's Advice": 0,
        "Adventurer's Experience": 3,
        "Hero's Wit": 42,
        "Mora": 60000,
        "BossItem": 4,
        "LocalSpecialty": 20,
        "Sliver": 0,
        "Fragment": 6,
        "Chunk": 0,
        "Gemstone": 0,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 12,
        "EnhancementMaterial3": 0,
    },
    {
        "Wanderer's Advice": 1,
        "Adventurer's Experience": 3,
        "Hero's Wit": 59,
        "Mora": 80000,
        "BossItem": 8,
        "LocalSpecialty": 30,
        "Sliver": 0,
        "Fragment": 0,
        "Chunk": 3,
        "Gemstone": 0,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 18,
        "EnhancementMaterial3": 0,
    },
    {
        "Wanderer's Advice": 2,
        "Adventurer's Experience": 2,
        "Hero's Wit": 80,
        "Mora": 100000,
        "BossItem": 12,
        "LocalSpecialty": 45,
        "Sliver": 0,
        "Fragment": 0,
        "Chunk": 6,
        "Gemstone": 0,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 12,
    },
    {
        "Wanderer's Advice": 4,
        "Adventurer's Experience": 0,
        "Hero's Wit": 171,
        "Mora": 120000,
        "BossItem": 20,
        "LocalSpecialty": 60,
        "Sliver": 0,
        "Fragment": 0,
        "Chunk": 0,
        "Gemstone": 6,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 24,
    },
]

weapon_ascension_requirements = [
    {
        "Mora": 10000,
        "AntiqueMat2": 5,
        "AntiqueMat3": 0,
        "AntiqueMat4": 0,
        "AntiqueMat5": 0,
        "AscensionMat2": 5,
        "AscensionMat3": 0,
        "AscensionMat4": 0,
        "EnhancementMaterial1": 3,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 0,
    },
    {
        "Mora": 20000,
        "AntiqueMat2": 0,
        "AntiqueMat3": 5,
        "AntiqueMat4": 0,
        "AntiqueMat5": 0,
        "AscensionMat2": 18,
        "AscensionMat3": 00,
        "AscensionMat4": 00,
        "EnhancementMaterial1": 12,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 0,
    },
    {
        "Mora": 30000,
        "AntiqueMat2": 0,
        "AntiqueMat3": 9,
        "AntiqueMat4": 0,
        "AntiqueMat5": 0,
        "AscensionMat2": 0,
        "AscensionMat3": 9,
        "AscensionMat4": 0,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 9,
        "EnhancementMaterial3": 0,
    },
    {
        "Mora": 45000,
        "AntiqueMat2": 0,
        "AntiqueMat3": 0,
        "AntiqueMat4": 5,
        "AntiqueMat5": 0,
        "AscensionMat2": 0,
        "AscensionMat3": 18,
        "AscensionMat4": 00,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 14,
        "EnhancementMaterial3": 0,
    },
    {
        "Mora": 55000,
        "AntiqueMat2": 0,
        "AntiqueMat3": 0,
        "AntiqueMat4": 9,
        "AntiqueMat5": 0,
        "AscensionMat2": 0,
        "AscensionMat3": 0,
        "AscensionMat4": 14,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 9,
    },
    {
        "Mora": 65000,
        "AntiqueMat2": 0,
        "AntiqueMat3": 0,
        "AntiqueMat4": 0,
        "AntiqueMat5": 6,
        "AscensionMat2": 0,
        "AscensionMat3": 0,
        "AscensionMat4": 27,
        "EnhancementMaterial1": 0,
        "EnhancementMaterial2": 0,
        "EnhancementMaterial3": 18,
    },
]

talent_ascension_requirements = [
    {
        "Mora": 12500,
        "Drop1": 6,
        "Drop2": 0,
        "Drop3": 0,
        "Book2": 3,
        "Book3": 0,
        "Book4": 0,
        "Crown": 0,
        "Weekly": 0,
    },
    {
        "Mora": 17500,
        "Drop1": 0,
        "Drop2": 3,
        "Drop3": 0,
        "Book2": 0,
        "Book3": 2,
        "Book4": 0,
        "Crown": 0,
        "Weekly": 0,
    },
    {
        "Mora": 25000,
        "Drop1": 0,
        "Drop2": 4,
        "Drop3": 0,
        "Book2": 0,
        "Book3": 4,
        "Book4": 0,
        "Crown": 0,
        "Weekly": 0,
    },
    {
        "Mora": 30000,
        "Drop1": 0,
        "Drop2": 6,
        "Drop3": 0,
        "Book2": 0,
        "Book3": 6,
        "Book4": 0,
        "Crown": 0,
        "Weekly": 0,
    },
    {
        "Mora": 37500,
        "Drop1": 0,
        "Drop2": 9,
        "Drop3": 0,
        "Book2": 0,
        "Book3": 9,
        "Book4": 0,
        "Crown": 0,
        "Weekly": 0,
    },
    {
        "Mora": 120000,
        "Drop1": 0,
        "Drop2": 0,
        "Drop3": 4,
        "Book2": 0,
        "Book3": 0,
        "Book4": 4,
        "Crown": 0,
        "Weekly": 1,
    },
    {
        "Mora": 260000,
        "Drop1": 0,
        "Drop2": 0,
        "Drop3": 6,
        "Book2": 0,
        "Book3": 0,
        "Book4": 6,
        "Crown": 0,
        "Weekly": 1,
    },
    {
        "Mora": 450000,
        "Drop1": 0,
        "Drop2": 0,
        "Drop3": 9,
        "Book2": 0,
        "Book3": 0,
        "Book4": 12,
        "Crown": 0,
        "Weekly": 2,
    },
    {
        "Mora": 700000,
        "Drop1": 0,
        "Drop2": 0,
        "Drop3": 12,
        "Book2": 00,
        "Book3": 00,
        "Book4": 16,
        "Crown": 1,
        "Weekly": 2,
    }, 
]

def calculate_total_requirements(ascensionPerLev: dict):
    total_ascension_requirement = {}

    for ascension in ascensionPerLev:
        for item, val in ascension.items():
            print(item in total_ascension_requirement)
            if item not in total_ascension_requirement:
                total_ascension_requirement[item] = 0
            total_ascension_requirement[item] += val
    return total_ascension_requirement

print(calculate_total_requirements(talent_ascension_requirements))